export enum Skill {
    acrobatics = 'acrobatics',
    astrophysics = 'astrophysics',
    athletics = 'athletics',
    computers = 'computers',
    deception = 'deception',
    insight = 'insight',
    intimidation = 'intimidation',
    investigation = 'investigation',
    lore = 'lore',
    mechanics = 'mechanics',
    medicine = 'medicines',
    performance = 'performance',
    perception = 'perception',
    persuasion = 'persuasion',
    slightOfHand = 'slight of hand',
    stealth = 'stealth',
    survival = 'survival',
    xenobiology = 'xenobiology',
}