enum Skill {
    acrobatics,
    astrophysics,
    athletics,
    computers,
    deception,
    insight,
    intimidation,
    investigation,
    lore,
    mechanics,
    medicine,
    perception,
    persuasion,
    slightOfHand,
    stealth,
    survival,
    xenobiology
}