export enum Skill {
    acrobatics = 'Acrobatics',
    astrophysics = 'Astrophysics',
    athletics = 'Athletics',
    computers = 'Computers',
    deception = 'Deception',
    insight = 'Insight',
    intimidation = 'Intimidation',
    investigation = 'Investigation',
    lore = 'Lore',
    mechanics = 'Mechanics',
    medicine = 'Medicines',
    performance = 'Performance',
    perception = 'Perception',
    persuasion = 'Persuasion',
    slightOfHand = 'Slight of hand',
    stealth = 'Stealth',
    survival = 'Survival',
    xenobiology = 'Xenobiology',
}